#ifndef __HDR_H__
#define __HDR_H__
#include <stdio.h>
#include <iostream>
#include <vector>
#include <thread>
#include <functional>
#include <mutex>
#include <chrono>
#include <future>
#include <sstream>
#include <cstdlib> 
#include <ctime> 
#endif //__HDR_H__
