#ifndef __HDR_H__
#define __HDR_H__
#include <iostream>
#include <vector>
#include <thread>
#include <functional>
#include <mutex>
#include <chrono>
#include <future>
#include <sstream>
#endif //__HDR_H__
